// Command export-role-scope-defaults exports public deployment policy from the
// runtime's single source of truth. It never reads credentials or grants roles.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/xufei5620/xingmang-platform/internal/platform/rolepermissions"
)

const sourcePath = "platform/internal/platform/rolepermissions/rolemap.go"

func export(format string, source []byte) ([]byte, error) {
	roles := rolepermissions.DefaultRoleScopeMap()
	for _, scopes := range roles {
		sort.Strings(scopes)
	}
	body, err := json.MarshalIndent(roles, "", "    ")
	if err != nil {
		return nil, err
	}
	switch format {
	case "json":
		return append(body, '\n'), nil
	case "python":
		source = bytes.ReplaceAll(source, []byte("\r\n"), []byte("\n"))
		return []byte(fmt.Sprintf("# Code generated by platform/cmd/export-role-scope-defaults; DO NOT EDIT.\n"+
			"# Runtime source: rolepermissions.DefaultRoleScopeMap(). No implicit grant/merge.\n"+
			"SOURCE_PATH = %q\nSOURCE_SHA256 = %q\nDEFAULT_ROLE_SCOPES = %s\n",
			sourcePath, fmt.Sprintf("%x", sha256.Sum256(source)), body)), nil
	default:
		return nil, fmt.Errorf("unsupported format %q", format)
	}
}

func main() {
	root := flag.String("root", "..", "monorepo root (default assumes cwd=platform)")
	format := flag.String("format", "json", "json or python")
	output := flag.String("output", "", "optional public output file; defaults to stdout")
	flag.Parse()
	source, err := os.ReadFile(filepath.Join(*root, sourcePath))
	if err == nil {
		var body []byte
		body, err = export(*format, source)
		if err == nil {
			if *output == "" {
				_, err = os.Stdout.Write(body)
			} else {
				err = os.WriteFile(*output, body, 0644)
			}
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
