package main

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// approvalEventFor names the exact approval event and target evidence
// narrative file each platform's capture feeds
// (docs/superpowers/specs/2026-08-28-platform-user-read-v2-design.md §0,
// docs/superpowers/plans/2026-08-28-platform-user-read-v2.md Task 4/5
// "Files: Create"). Getting a reviewer from "I have a redacted JSON file"
// to "I know exactly which approval document this is for" without another
// engineering step is this function's entire job.
func approvalEventFor(platform string) (event, template, evidenceDoc, testdataDir string) {
	switch platform {
	case PlatformSub2API:
		return "SUB2_REAL_APPROVAL", "docs/approvals/SUB2_REAL_APPROVAL.md",
			"docs/evidence/EV-2026-08-28-platformusers-sub2api-v2-shape.md",
			"connectors/platformusers/testdata/sub2api/"
	case PlatformNewAPI:
		return "NEWAPI_REAL_APPROVAL", "docs/approvals/NEWAPI_REAL_APPROVAL.md",
			"docs/evidence/EV-2026-08-28-platformusers-newapi-v2-shape.md",
			"connectors/platformusers/testdata/newapi/"
	default:
		return "", "", "", ""
	}
}

func renderCaptureReadme(report captureReport, dataFiles []evidenceFile, sums map[string]string) []byte {
	event, template, evidenceDoc, testdataDir := approvalEventFor(report.Platform)

	var b strings.Builder
	fmt.Fprintf(&b, "# Evidence capture: %s real-sample probe\n\n", report.Platform)
	fmt.Fprintf(&b, "Generated by `cmd/evidence-capture capture` at %s.\n\n", report.CapturedAt.Format(time.RFC3339))
	fmt.Fprintf(&b, "This directory is raw material for a product+security review under "+
		"`docs/superpowers/specs/2026-08-28-platform-user-read-v2-design.md` §0/§10. "+
		"**It is not an approval by itself.** A human reviewer must still read this "+
		"directory and sign `%s` (%s) before any real %s reader can be implemented. "+
		"See `docs/runbooks/USERS-REAL-APPROVAL.md`.\n\n", template, event, report.Platform)

	anyBlocked := false
	anyFailed := false
	for _, r := range report.Results {
		if r.ComplianceBlocked {
			anyBlocked = true
		} else if r.Err != nil {
			anyFailed = true
		}
	}
	if anyBlocked {
		fmt.Fprintln(&b, "> **BLOCKED: AdminComplianceGuard.** At least one request below got "+
			"HTTP 423. The account behind this run's credential has not completed compliance "+
			"acceptance in the Sub2API admin console. This tool never sends that POST itself - "+
			"a human must do it out of band, then this capture must be re-run. See "+
			"`docs/runbooks/USERS-REAL-APPROVAL.md`.")
	} else if anyFailed {
		fmt.Fprintln(&b, "> **Partial capture: at least one request below failed.** Evidence for "+
			"the requests that succeeded is still included; see the table below for what to "+
			"retry.")
	}

	fmt.Fprintln(&b, "## What was requested")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Every request this run could ever make is fixed in `cmd/evidence-capture`'s "+
		"source (`planFor` in `plan.go`) - there is no flag that lets a caller supply an "+
		"arbitrary path. Only `GET`/read requests; see `mustNotBeMockRoute` for the routes this "+
		"tool refuses to call even by mistake.")
	fmt.Fprintln(&b, "| purpose | method | path | status | latency (ms) | outcome |")
	fmt.Fprintln(&b, "|---|---|---|---|---|---|")
	for _, r := range report.Results {
		outcome := "ok"
		if r.ComplianceBlocked {
			outcome = "BLOCKED (423 AdminComplianceGuard)"
		} else if r.Err != nil {
			outcome = "FAILED: " + escapeTableCell(r.Err.Error())
		}
		fmt.Fprintf(&b, "| %s | %s | `%s` | %d | %d | %s |\n",
			r.Step.Purpose, r.Step.Method, r.Step.requestLine(), r.Status, r.LatencyMS, outcome)
	}
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Upstream instance")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- endpoint host: `%s`\n", report.Endpoint)
	fmt.Fprintf(&b, "- target allowlist: %s\n", codeList(report.Allowlist))
	fmt.Fprintf(&b, "- credential ref: `%s` (reference only - the plaintext token was resolved "+
		"in memory for the duration of these requests and never written to any file, log line, "+
		"or error message this tool produces)\n", report.CredentialRef)
	fmt.Fprintf(&b, "- environment label: `%s`\n", report.Environment)
	if report.Version != "" {
		fmt.Fprintf(&b, "- upstream version string: `%s`\n", report.Version)
	}
	if report.Platform == PlatformNewAPI && report.QuotaPerUnit > 0 {
		fmt.Fprintf(&b, "- quota_per_unit at capture time: `%d` (runtime-mutable; re-observe on "+
			"every real read, do not hardcode - see `connectors/platformusers/upstream.go`)\n", report.QuotaPerUnit)
	}
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Fields captured (redacted) vs. dropped")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- kept (redacted, present in `users_page.redacted.json` / "+
		"`user_detail.redacted.json`): %s\n", codeList(report.Kept))
	fmt.Fprintf(&b, "- observed on the wire but **not captured** (name only - no value from these "+
		"fields ever left this process): %s\n", codeListOrNone(report.Dropped))
	fmt.Fprintln(&b, "\nAdding a dropped field to the redacted evidence requires adding it, by name, "+
		"to that platform's `ItemPolicy` in `sub2api.go`/`newapi.go` with an explicit redaction "+
		"rule - reviewed the same way as any other code change, not a flag on this tool.")

	fmt.Fprintln(&b, "## Redaction applied")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "- `email` -> `platformusers.MaskEmail` (the platform's own reviewed masking: "+
		"local part reduced to 0-2 leading characters, domain kept in full)")
	fmt.Fprintln(&b, "- `id` -> one-way per-run pseudonym, `u_` + 16 hex chars of "+
		"`sha256(salt || \"id\" || id)` - stable within this run only, not reversible without the "+
		"salt below, and the salt is not reused across runs")
	fmt.Fprintln(&b, "- `username`/`display_name` -> one-way per-run pseudonym, `name_` + 12 hex "+
		"chars, independent hash domain from `id` (an id and a name with the same raw text never "+
		"produce the same pseudonym)")
	fmt.Fprintln(&b, "- `balance`/`quota` -> every digit zeroed (a bare JSON number's leading digit "+
		"becomes 1, not 0, only because JSON forbids a leading zero on a multi-digit number - "+
		"every other digit is 0); sign, decimal point position and whether the upstream sent a "+
		"JSON string or a bare JSON number are all preserved, so the *shape* evidence Task 4/5 "+
		"needs survives while the real account balance does not")
	fmt.Fprintln(&b, "- `status`, `last_active_at`/`last_login_at`, NewAPI's `DeletedAt` -> passed "+
		"through unchanged (small known value spaces / soft-delete markers, not PII)")
	fmt.Fprintf(&b, "\ncapture salt for this run (not a credential; do not reuse across runs): `%s`\n\n", report.SaltHex)

	fmt.Fprintln(&b, "## Files and sha256 (also in `SHA256SUMS`)")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| file | sha256 |")
	fmt.Fprintln(&b, "|---|---|")
	for _, f := range dataFiles {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", f.Name, sums[f.Name])
	}
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Feeds into")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- `%s` - the narrative evidence document "+
		"`docs/superpowers/plans/2026-08-28-platform-user-read-v2.md` Task 4/5 requires; a human "+
		"writes its prose citing this directory's path and the sha256 sums above.\n", evidenceDoc)
	fmt.Fprintf(&b, "- `%susers_page.redacted.json` <- copy this run's `users_page.redacted.json` "+
		"verbatim (same envelope shape).\n", testdataDir)
	fmt.Fprintf(&b, "- `%suser_detail.redacted.json` <- copy this run's `user_detail.redacted.json` "+
		"verbatim.\n", testdataDir)
	fmt.Fprintf(&b, "- `%s` (blank signature lines for 产品 and 安全) - the approval text itself; "+
		"this directory's path is what goes in its evidence-path fields.\n", template)

	return []byte(b.String())
}

func renderReqlogReadme(retention retentionEvidence, tokenEv tokenMapEvidence, assoc associationEvidence, dayDirs []string, sums map[string]string, now time.Time, saltHex string) []byte {
	var b strings.Builder
	fmt.Fprintln(&b, "# Evidence capture: reqlog stable UserRef (Task 8)")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "Generated by `cmd/evidence-capture reqlog` at %s, reading a local copy of "+
		"reqlog's `index.jsonl` files and `tokenmap.json` - no network access, no live recorder "+
		"or upstream instance was touched to produce this directory.\n\n", now.Format(time.RFC3339))
	fmt.Fprintln(&b, "This directory is raw material for a product+security review under "+
		"`docs/superpowers/specs/2026-08-28-platform-user-read-v2-design.md` §0/§10. "+
		"**It is not an approval by itself.** A human reviewer must still read this directory and "+
		"sign `docs/approvals/REQLOG_USERREF_APPROVAL.md` (event `REQLOG_USERREF_APPROVAL`) "+
		"before reqlog's stable UserRef (Task 8) can be implemented. See "+
		"`docs/runbooks/USERS-REAL-APPROVAL.md`.")

	fmt.Fprintln(&b, "## Headline finding: today's tokenmap cannot supply a stable UserRef")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "`tokenmap.json` in this run has %d entries, all shaped "+
		"`<username-or-email>@<source>` (%d `@newapi`, %d `@sub2api`, %d with an unrecognized "+
		"suffix). That shape has no field for an upstream numeric/opaque user id. "+
		"`cmd/reqlog-recorder/tokenmap.go`'s own export queries only `SELECT` username/email from "+
		"both upstream databases, never `id`, even though both queries already `JOIN` on it. "+
		"**This is a schema-level fact** - true of any tokenmap this recorder produces, not just "+
		"this sample - and it means Task 8 cannot ship a `platform.UserRef{Platform, ID}` from "+
		"this pipeline without first changing that export query to also select the upstream id. "+
		"See `retention_and_association.json` for the counts backing this.\n\n", tokenEv.TotalEntries, tokenEv.SuffixNewAPI, tokenEv.SuffixSub2API, tokenEv.MalformedSuffix)

	fmt.Fprintln(&b, "## Retention")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- day directories found: %d\n", retention.DayDirsFound)
	if retention.DayDirsFound > 0 {
		fmt.Fprintf(&b, "- oldest: `%s`, newest: `%s`, observed span: %d day(s)\n", retention.OldestDay, retention.NewestDay, retention.ObservedSpanDays)
		fmt.Fprintf(&b, "- configured/expected retention: %d day(s); observed span within that: %v\n", retention.ConfiguredRetentionDays, retention.SpanWithinConfigured)
	}
	fmt.Fprintf(&b, "- %s\n\n", retention.Note)

	fmt.Fprintln(&b, "## Cursor semantics")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "%s\n\n", cursorSemanticsNote)

	fmt.Fprintln(&b, "## Association (per-record resolution outcome, counts only)")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "| total records | resolved via tokenmap | no token prefix recorded | prefix present but not in tokenmap |\n")
	fmt.Fprintln(&b, "|---|---|---|---|")
	fmt.Fprintf(&b, "| %d | %d | %d | %d |\n\n", assoc.TotalRecords, assoc.ResolvedCount, assoc.NoPrefixCount, assoc.UnresolvedPrefixCount)
	fmt.Fprintln(&b, "\"Resolved\" only means the record's token prefix had a matching entry in "+
		"`tokenmap.json` - given the headline finding above, a resolved record still only proves "+
		"a display identifier, not a stable id. No username or email from either the index or the "+
		"tokenmap appears anywhere in this directory, resolved or not.")

	fmt.Fprintln(&b, "## Redacted sample")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "`index_sample.redacted.jsonl` holds up to the requested `--sample-size` rows, "+
		"newest day first. Per row: `id` -> one-way per-run hash (`rec_` + 16 hex chars), "+
		"`client_ip` -> `connectors/reqlog.MaskIP` (the platform's own reviewed masking, keeps "+
		"/24 or the IPv6 /48), `token_prefix` -> one-way per-run hash (`pfx_` + 12 hex chars) plus "+
		"a `username_resolved` boolean - never the prefix itself, never the resolved identity. "+
		"`ua`, `upstream_request_id`, `resp_body_id`, `end_note`, `preview`, `path` and `method` "+
		"are dropped entirely: none are needed for this evidence door, and `preview`/`end_note` "+
		"in particular can carry excerpted request/response content on the real recorder - this "+
		"subcommand never reads a record's full body file (`<id>.json.gz`) at all, redacted or "+
		"not.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "capture salt for this run (not a credential; do not reuse across runs): `%s`\n\n", saltHex)

	fmt.Fprintln(&b, "## Day directories observed")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "%s\n\n", codeListOrNone(dayDirs))

	fmt.Fprintln(&b, "## Files and sha256 (also in `SHA256SUMS`)")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| file | sha256 |")
	fmt.Fprintln(&b, "|---|---|")
	names := make([]string, 0, len(sums))
	for name := range sums {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", name, sums[name])
	}
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Feeds into")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "- `docs/approvals/REQLOG_USERREF_APPROVAL.md` (blank signature lines for "+
		"产品 and 安全) - this directory's path and the sha256 sums above go in its evidence-path "+
		"fields.")
	fmt.Fprintln(&b, "- Whoever prepares the REQLOG_USERREF_APPROVAL evidence package should read "+
		"the headline finding above before assuming Task 8 is a small change - see "+
		"`docs/handoffs/slices/XM-USERS-V2-real-detail.md`'s follow_ups for the same conclusion "+
		"reached independently by reading `cmd/reqlog-recorder/tokenmap.go`'s SQL directly.")

	return []byte(b.String())
}

func codeList(items []string) string {
	if len(items) == 0 {
		return "(none)"
	}
	out := make([]string, len(items))
	for i, it := range items {
		out[i] = "`" + it + "`"
	}
	return strings.Join(out, ", ")
}

func codeListOrNone(items []string) string {
	if len(items) == 0 {
		return "(none observed)"
	}
	return codeList(items)
}

// escapeTableCell keeps an error message (this tool's own text, or a
// wrapped Go stdlib/connector error - never an upstream response body, see
// fetchOne) from breaking a Markdown table row.
func escapeTableCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
