// Command console-assertion-keygen generates one Ed25519 keypair for
// CR-0006/XM-INVCON1's console-assertion signing domain and prints the
// two artifacts an operator needs to bring the key into service:
//
//  1. The public manifest entry (contracts/auth/console-assertion-keyring.
//     v1.json shape) -- non-secret, safe to commit in *both*
//     xingmang-platform and the invoice-system repository (the technical
//     spec requires a byte-identical reviewed copy in each).
//  2. The private key's one-time plaintext value -- printed to stdout
//     exactly once, exactly like cmd/staff-bootstrap's one-time initial
//     password, and for the same reason: this is a Platform Lifecycle
//     Operation (constitution clause 3), not an HTTP write path, so there is
//     no session/actor available to hand it to a normal Action. An operator
//     must store it through the existing credential.secret.upsert Action
//     (POST /api/v1/actions/credential.secret.upsert/versions/1/execute,
//     credential_ref="secret://console-assertion/signing-key-<key_id>") --
//     this command never touches the secret store itself, it only prints
//     what to paste there.
//
// This tool never contacts a database, a running platform-api process, or
// any secret store: it is pure key generation plus JSON formatting, so it
// can be run on an operator's own machine ahead of a deploy, exactly as
// fleet_keyring.go's own pinned keys were presumably generated once and
// never regenerated by CI.
package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/xufei5620/xingmang-platform/internal/platform/consoleassertion"
)

func main() {
	keyID := flag.String("key-id", "", "manifest key_id, e.g. 2026-09 (also becomes the JWS kid)")
	validFromFlag := flag.String("valid-from", "", "RFC3339 UTC (default: now, truncated to the second)")
	validityDays := flag.Int("validity-days", 365, "days from valid-from until valid-until")
	manifestPath := flag.String("manifest", "", "existing contracts/auth/console-assertion-keyring.v1.json to append the new record into and rewrite (optional; omit to only print)")
	flag.Parse()

	if strings.TrimSpace(*keyID) == "" {
		fmt.Fprintln(os.Stderr, "--key-id is required")
		os.Exit(2)
	}
	if *validityDays <= 0 {
		fmt.Fprintln(os.Stderr, "--validity-days must be positive")
		os.Exit(2)
	}

	validFrom := time.Now().UTC().Truncate(time.Second)
	if strings.TrimSpace(*validFromFlag) != "" {
		parsed, err := time.Parse(time.RFC3339, strings.TrimSpace(*validFromFlag))
		if err != nil {
			fmt.Fprintf(os.Stderr, "--valid-from: %v\n", err)
			os.Exit(2)
		}
		validFrom = parsed.UTC()
	}
	validUntil := validFrom.Add(time.Duration(*validityDays) * 24 * time.Hour)

	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generating Ed25519 keypair failed: %v\n", err)
		os.Exit(1)
	}

	record, err := consoleassertion.NewPublicKeyRecord(*keyID, pub, validFrom, validUntil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "building manifest record failed: %v\n", err)
		os.Exit(1)
	}

	if strings.TrimSpace(*manifestPath) != "" {
		if err := writeManifest(*manifestPath, record); err != nil {
			fmt.Fprintf(os.Stderr, "updating %s failed: %v\n", *manifestPath, err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s (key_id=%s)\n\n", *manifestPath, record.KeyID)
	}

	entryJSON, err := consoleassertion.MarshalManifestJSON([]consoleassertion.PublicKeyRecord{record})
	if err != nil {
		fmt.Fprintf(os.Stderr, "encoding manifest entry failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("=== public manifest entry (safe to commit; copy into BOTH repositories' contracts/auth/console-assertion-keyring.v1.json) ===")
	fmt.Println(string(entryJSON))
	fmt.Println("=== private key (ONE-TIME output; never commit, never log again) ===")
	fmt.Printf("credential_ref: secret://console-assertion/signing-key-%s\n", record.KeyID)
	fmt.Printf("secret_value (base64 Ed25519 seed, paste exactly): %s\n", seedBase64(priv))
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. As an operator with credential.manage, call credential.secret.upsert@1 with the")
	fmt.Println("     credential_ref and secret_value printed above (never through this tool -- it has no")
	fmt.Println("     session/actor to attribute the write to; see constitution clause 3 on Platform")
	fmt.Println("     Lifecycle Operations).")
	fmt.Println("  2. Set XM_INVOICE_CONSOLE_ASSERTION_KEY_REF to the credential_ref printed above and")
	fmt.Println("     redeploy platform-api.")
	fmt.Println("  3. Commit the public manifest entry into contracts/auth/console-assertion-keyring.v1.json")
	fmt.Println("     in xingmang-platform, and hand the same entry to the invoice-system team to commit")
	fmt.Println("     into their copy of the same file -- both must match exactly (spec: \"两仓库各存一份只读副本\").")
}

func seedBase64(priv ed25519.PrivateKey) string {
	return base64.StdEncoding.EncodeToString(priv.Seed())
}

// writeManifest reads an existing manifest (or starts empty if the file does
// not exist yet), appends record in sorted position, and rewrites the file.
func writeManifest(path string, record consoleassertion.PublicKeyRecord) error {
	var existing []consoleassertion.PublicKeyRecord
	raw, err := os.ReadFile(path)
	switch {
	case err == nil:
		existing, err = consoleassertion.LoadKeyringJSON(raw)
		if err != nil {
			return fmt.Errorf("existing manifest is invalid: %w", err)
		}
	case os.IsNotExist(err):
		existing = nil
	default:
		return err
	}
	for _, r := range existing {
		if r.KeyID == record.KeyID {
			return fmt.Errorf("key_id %q already present in %s", record.KeyID, path)
		}
	}
	all := append(existing, record)
	sort.Slice(all, func(i, j int) bool { return all[i].KeyID < all[j].KeyID })
	out, err := consoleassertion.MarshalManifestJSON(all)
	if err != nil {
		return err
	}
	return os.WriteFile(path, out, 0o644)
}
