# Code generated by platform/cmd/export-role-scope-defaults; DO NOT EDIT.
# Runtime source: rolepermissions.DefaultRoleScopeMap(). No implicit grant/merge.
SOURCE_PATH = "platform/internal/platform/rolepermissions/rolemap.go"
SOURCE_SHA256 = "d87f6bd7002317a3f933c2ccc09da3263fde9eb1d3d49e2121db1d9f69ca8b74"
DEFAULT_ROLE_SCOPES = {
    "admin": [
        "action.read",
        "alerts.alert.manage",
        "alerts.silence.manage",
        "approval.decide",
        "approval.read",
        "assurance.probe.manage",
        "assurance.probe.run",
        "audit.read",
        "card.issue",
        "card.manage",
        "card.read",
        "card.reveal",
        "connector.manage",
        "credential.manage",
        "extapp.manage",
        "finance.read",
        "finance.recharge_ratio.manage",
        "finance.subscription.manage",
        "finance.token_map.manage",
        "finance.upstream_account.manage",
        "fund.limit.manage",
        "integration.manage",
        "integration.read",
        "ops.read",
        "platform.users.read",
        "publishing.manage",
        "publishing.read",
        "registry.connection.manage",
        "registry.connector.manage",
        "registry.read",
        "registry.service.manage",
        "request.read",
        "server.manage",
        "sms.manage",
        "sms.read",
        "sms.reveal",
        "staff.manage",
        "ui.saved_view.manage"
    ],
    "approval-l4": [
        "approval.decide",
        "approval.l4"
    ],
    "assurance-probe-admin": [
        "assurance.probe.kill_switch"
    ],
    "content-publisher": [
        "publishing.publish",
        "publishing.read"
    ],
    "credential-admin": [
        "connector.manage",
        "credential.manage"
    ],
    "fund-operator": [
        "fund.address.manage",
        "fund.withdraw"
    ],
    "key-metadata-reader": [
        "platform.user_keys.read"
    ],
    "request-content-reader": [
        "request.content.read"
    ],
    "sms-operator": [
        "sms.purchase"
    ],
    "staff": [
        "ops.read",
        "registry.read",
        "ui.saved_view.manage"
    ]
}
